/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_chillcrew_archivec_core_ArchivecCore */

#ifndef _Included_ua_chillcrew_archivec_core_ArchivecCore
#define _Included_ua_chillcrew_archivec_core_ArchivecCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_chillcrew_archivec_core_ArchivecCore
 * Method:    extractFilesNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_ua_chillcrew_archivec_core_ArchivecCore_extractFilesNative
  (JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
